# Generated by Django 5.1.3 on 2025-05-04 08:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名稱')),
                ('location', models.TextField(verbose_name='公司地址')),
                ('latitude', models.TextField(verbose_name='公司位置緯度')),
                ('longitude', models.TextField(verbose_name='公司位置經度')),
                ('radius', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GPS合法範圍半徑')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='員工編號')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='員工電話')),
                ('address', models.TextField(blank=True, null=True, verbose_name='員工地址')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmpCompanyRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.BooleanField(verbose_name='在職狀態')),
                ('hire_date', models.DateField(verbose_name='入職日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='離職日期')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='attendance.companies', verbose_name='公司編號')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='員工編號')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='考勤日期')),
                ('checkin_time', models.DateTimeField(verbose_name='上班打卡時間')),
                ('checkout_time', models.DateTimeField(verbose_name='下班打卡時間')),
                ('checkin_location', models.TextField(verbose_name='上班打卡位置')),
                ('checkout_location', models.TextField(verbose_name='下班打卡位置')),
                ('work_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='上班總時數')),
                ('relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.empcompanyrel', verbose_name='關聯編號')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='請假開始時間')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='請假結束時間')),
                ('leave_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='請假總時數')),
                ('relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='attendance.empcompanyrel', verbose_name='關聯編號')),
            ],
        ),
    ]
