# Generated by Django 5.1.3 on 2025-05-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverecords',
            old_name='end_datetime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='leaverecords',
            old_name='start_datetime',
            new_name='start_time',
        ),
    ]
