# Generated by Django 5.1.3 on 2025-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_end_datetime_leaverecords_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecords',
            name='leave_reason',
            field=models.TextField(blank=True, null=True, verbose_name='請假原因'),
        ),
    ]
