# Generated by Django 5.1.3 on 2025-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaverecords_leave_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecords',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='上班總時數'),
        ),
        migrations.AlterField(
            model_name='leaverecords',
            name='leave_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='請假總時數'),
        ),
    ]
