# Generated by Django 5.1.3 on 2025-05-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerecords_work_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecords',
            options={'verbose_name_plural': '出缺勤紀錄'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='empcompanyrel',
            options={'verbose_name_plural': '員工與公司關係'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': '員工'},
        ),
        migrations.AlterModelOptions(
            name='leaverecords',
            options={'verbose_name_plural': '請假紀錄'},
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='location',
            new_name='address',
        ),
    ]
