# Generated by Django 5.1.3 on 2025-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecords_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='address',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='員工電子郵件'),
        ),
    ]
